### ISSUE TITLE
Add ark command line sync option

### ISSUE THREAD

**Issue by mbroome** [heptio/ark#104]
It would be useful to have the ark client be able to trigger the server to sync with the storage backend without having to scale down/up or kill the server pod.  In the case where there are two different kubernetes clusters using the same centralized storage backend, it would be nice to be able to see backups at will across all clusters at will.

**Comment by ncdc** [comment]
There are a couple of ways we could do this:
1. User submits a custom resource similar to DownloadRequest, something like a BackupSyncRequest, that a controller watches for and reacts to
1. User connects to an http server bound only to localhost in the Ark server pod (either via `kubectl port-forward` or the pods proxy api)

How often do you see needing to do this? Would setting the sync period to 1 minute be acceptable (although that would increase the # of object storage requests a lot)?

**Comment by mbroome** [comment]
I see it as a pretty rare occasion which is why I was thinking have it manually triggered by the ark client as needed.  That's why I did not adjust the sync period as it's not going to be a common occurrence.  But when you need to restore, its needed asap.

**Comment by ncdc** [comment]
@mbroome are you thinking something along the lines of `ark backup sync` or `ark sync backups`? Is it clear enough that that syncs from object storage to Backups? Do we need something a bit more informative in its name?

**Comment by rosskukulinski** [comment]
`As a user with two clusters sharing a storage backend, I would like to see backups taken from one cluster quickly appear on the other cluster.`

Right now, the ark backup sync period defaults to 30 minutes.  If you create a backup using ClusterA, it may take up to 30 minutes for the Backup to appear in ClusterB.

@ncdc what do you think about `ark backup (get|describe) --force-sync` rather than adding a new `sync` command?

**Comment by ncdc** [comment]
@rosskukulinski however we do it, it's going to require a new CRD because the `ark` client is going to have to send a request to the server to ask it to sync.

It sounds like you're possibly suggesting the ability to sync a single backup by name? The sync process syncs all backups (we basically get a "directory" listing from object storage), so doing a single backup sync would be new code to add.

**Comment by rosskukulinski** [comment]
Ah, yes, you're right -- tying the sync command to the (get|describe) might get confusing if the user specifies a label selector.

+1 for separate `sync` command (or alternatively named function)

**Comment by skriss** [comment]
I think this can be closed given #785 which runs the sync much more frequently while using fewer cloud-provider calls. @ncdc @rosskukulinski agree?

**Comment by ncdc** [comment]
👍

**Comment by rosskukulinski** [comment]
@skriss +1 from me, but can we make sure we have docs (cc: @Bradamant3) somewhere describing the expected sync behavior in terms of timing
