### ISSUE TITLE
Support pre/post backup and restore hooks

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#172]
These will be pre and post the entire backup. Options for what to run include
- webhooks
- exec command in container
- create new run-once pod

**Comment by ncdc** [comment]
This can be achieved with external tooling watching for new/completed backups and restores. Will reopen if needed.

**Comment by manast** [comment]
@ncdc with watching do you mean using polling or is there any other mechanism that uses push instead?

**Comment by ashish-amarnath** [comment]
@manast Watching doesn't mean active polling in your tooling. You can use the dynamic informer apis in kubernetes client-go that allows you to register handlers for create, update, delete events for objects of a resource type. In this case you you would create a dynamic informer of the `backup` velero CRD and register update event handler. In the handler function, you would inspect the `Phase` field in the status and run custom logic based on what you find there.

**Comment by manast** [comment]
all right, I got it, thanks for the reply.

**Comment by manast** [comment]
Ok, although I understand exactly what you meant, I noticed there is zero documentation for the API regarding informers, and specially in the official javascript library (the one I am using), there is one example however since no documentation is available I do not know how to extrapolate it to registering the watchers for velero backup. Sorry to bother you with this, but if you know how to do it it would be great if you could give me a hint, this is the example code: ```ts
// tslint:disable:no-console
import * as k8s from '@kubernetes/client-node';

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

const listFn = () => k8sApi.listNamespacedPod('default');

const informer = k8s.makeInformer(kc, '/api/v1/namespaces/default/pods', listFn);

informer.on('add', (obj: k8s.V1Pod) => { console.log(`Added: ${obj.metadata!.name}`); });
informer.on('update', (obj: k8s.V1Pod) => { console.log(`Updated: ${obj.metadata!.name}`); });
informer.on('delete', (obj: k8s.V1Pod) => { console.log(`Deleted: ${obj.metadata!.name}`); });
informer.on('error', (err: k8s.V1Pod) => {
  console.error(err);
  // Restart informer after 5sec
  setTimeout(() => {
    informer.start();
  }, 5000);
});

informer.start();
```
This is my loose attempt to register the informer: 
```ts
import k8s from "@kubernetes/client-node";

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

const listFn = () => k8sApi.listNamespacedPod("default");

const informer = k8s.makeInformer(
  kc,
  "velero.io/v1/Backup",
  listFn
);
```

obviously the listFn is wrong for particular case, also as I understand I should specify a watchFn instead but couldn't find any examples for that...

**Comment by manast** [comment]
Ok, just for the record in case some other newbie wonders how to do this:
```
curl -X GET $HOST/apis/velero.io/v1/namespaces/velero/backups/?watch=1 --header "Authorization: Bearer $TOKEN" --insecure
```
That will open a stream and the events will be emitted as the occur.  Most libraries support some kind of watching, but I did not have any success with the javascript library so I implemented my own watcher.

**Comment by ashish-amarnath** [comment]
@manast Sorry about not responding sooner.
I haven't used the java script client much, but I would give the example here https://github.com/kubernetes-client/javascript/blob/master/examples/typescript/informer/informer.ts a try.

**Comment by manast** [comment]
@ashish-amarnath thank you for your answer. I tried a similar code to the one you pasted but I could not get the watch functionality to work, thats why settled on using my own.
The reason I am using javascript is because my backend is in typescript and it is easier for me to watch the changes of velero backups from there.

**Comment by manast** [comment]
ah, and regarding the informer, I spend a lot of time trying to make that work too, went through the source code to understand how it works, creating my own listenFn, but I gave up at the end.

**Comment by manast** [comment]
ah, I apologize, I was an idiot and missed that I did not have this uncommented: 
```
// setTimeout(() => { req.abort(); }, 20 * 1000);
```
so it works as expected :).
