### ISSUE TITLE
Volume snapshots don't include informative metadata

### ISSUE THREAD

**Issue by totemcaf** [heptio/ark#278]
Currently when a Snapshot is created in AWS due to a Backup, the snapshot has no name nor description. It has only a label pointing to Ark: "tag-key=ark-snapshot"

Having lots of snapshots will be difficult to see why some snapshot is for.

The idea is to add a name, and a description adding more data, for example the Backup name and/or the POD's name owning the PVC. Additional tags can also be added.

**Comment by ncdc** [comment]
@skriss let's incorporate this into the backup target design

**Comment by activeshadow** [comment]
It would also be great if Ark could capture any existing tags on AWS volumes. Here's why:

When Kubernetes creates volumes in AWS (and probably other cloud providers too) for backing PVs, it adds multiple tags to the volumes (KubernetesCluster, Name, kubernetes.io/created-for/pv/name, kubernetes.io/created-for/pvc/name, etc). When an AWS cluster is managed by kops, the IAM policy assigned to the Kubernetes master(s) relevant to mounting volumes to nodes includes a condition for the `KubernetesCluster` resource tag. If the tag doesn't exist, then the pods using the PVCs cannot start since the Kubernetes master(s) cannot mount the volumes to the nodes.

One scenario that will have to be addressed is when Ark is being used to migrate PVs from one cluster to another (ie. when the `KubernetesCluster` tag value will need to be different).

**Comment by ftoresan** [comment]
I'm facing the same issue with kops managed clusters.

Would this be a good case for the use of plugins?  
Or the change must be done in the EBS backup/restore code?

**Comment by ncdc** [comment]
@ftoresan this has to be done in the core Ark server code, possibly with some adjustments to some of the cloud plugin code.
