### ISSUE TITLE
Feature Request: Sane default schedule implementation

### ISSUE THREAD

**Issue by lypht** [heptio/ark#347]
As a user, I wish to have a default schedule implementation, where running `ark create schedule foo` creates an ark schedule that runs once a day, if I do not add the currently required `--schedule` flag.

**Comment by nrb** [comment]
Cribbing from the [jenkins code](https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/triggers/TimerTrigger/help-spec.jelly#L40), they use `H` to allow the system to spread jobs out for the user, as opposed to configuring specific and possibly overlapping times.

A similar approach would be useful in order to spread usage more evenly.

**Comment by ncdc** [comment]
I don't think we're interested in pursuing this. I fear it would provide more confusion than benefit. Any objections to closing it @lypht ?

**Comment by lypht** [comment]
Closing to prevent confusion.
