### ISSUE TITLE
Can I use ark to do disaster recovery between 2 clusters?

### ISSUE THREAD

**Issue by haoqing0110** [heptio/ark#370]
For example, I have 2 clusters, cluster A and cluster B.  
Backup cluster A with ark, can I restore the backup in another cluster B? Cluster B has different hostname, IP, event the number may be different.

**Comment by ncdc** [comment]
Hi @haoqing0110, yes you can! Please see https://github.com/heptio/ark/blob/v0.7.1/docs/use-cases.md for a bit more detail. Basically you use the same Ark `Config` for cluster B, but we recommend setting `restoreOnlyMode: true`. Install Ark into cluster B and soon you'll see that all of the backups you took from cluster A show up in cluster B. You can then run `ark restore create` against cluster B.

**Comment by haoqing0110** [comment]
@ncdc Cool! 
I read it, still have one question. Can it restore the cluster status like host label and taint? I mean host name and IP are different, how does it work?

**Comment by ncdc** [comment]
@haoqing0110 we purposefully do not restore nodes. It does not make sense to create a node from a backup because whatever nodes are currently registered for the cluster are the correct set of nodes.

One option is to define your target node layout (# of nodes, labels, taints, etc) in source control, and use some sort of automation tooling (ansible, terraform, etc) to ensure you have the desired set of nodes.

Maybe there's also some kind of story here, to combine an Ark backup with some additional metadata like node labels, so that when you restore, you get the desired cluster state. I'm not sure exactly what this might look like, though...

cc @jbeda

**Comment by jbeda** [comment]
One thing worth looking at is the emerging work around the cluster API.  This is the idea of using k8s concepts to drive the shape of the cluster itself.  These will take the form of custom resources and are compatible with the Ark model.  

This stuff is still a bit early though.  

kube-deploy is one of the projects looking at this.  I did a TGIK8s on this a while back that covers some of the ideas: https://www.youtube.com/watch?v=f_ANRYIXFgI&list=PLvmPtYZtoXOENHJiAQc6HmV2jmuexKfrJ&t=457s&index=21.  Look in the description for links to relevant projects/pages.

**Comment by haoqing0110** [comment]
@ncdc @jbeda Thank you for answering! Helps a lot.
