### ISSUE TITLE
Add Azure MSI support

### ISSUE THREAD

**Issue by jcrowthe** [heptio/ark#379]
Azure's [Managed Service Identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/overview) is supported in upstream Kubernetes as an alternative to utilizing a service principal for the authorization to the backend Azure cloud provider. 

This is a request to support MSI, allowing users on MSI-enabled clusters to run Ark without requiring an additional service principal.

**Comment by ncdc** [comment]
Hi @jcrowthe, thanks for the feature request. We'll evaluate and get back to you soon!

cc @paulbouwer @jimzim @noelbundick

**Comment by jcrowthe** [comment]
Any update available yet?

**Comment by jcrowthe** [comment]
@ncdc Hey, any updates on MSI support?

**Comment by ncdc** [comment]
@jcrowthe nothing new to report. We'll probably get our Azure SDK updated to the latest stable version first, then we could consider this.

**Comment by rosskukulinski** [comment]
“Managed Service Identity (MSI) is a public preview feature of Azure Active Directory.” -- What’s the Azure roadmap to launch this beyond a preview feature?  Is this similar to how GKE can provide API credential access to specific features (storage, dns, etc) to clusters?

**Comment by paulbouwer** [comment]
@ncdc @rosskukulinski @jcrowthe 

Managed Service Identity is definitely something we should support in Ark - both from a security and user experience point of view. However, I think we need to start a wider discussion about how best to implement this wrt Ark and the experience we want to deliver to end-users.

**acs-engine (MSI enabled)**

The MSI here has [System assigned identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/qs-configure-cli-windows-vmss#system-assigned-identity).

The master nodes are assigned an MSI that has the [Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#contributor) role scoped to the Resource Group. The auth tokens for this identity can be retrieved from the metadata endpoint and essentially provide root/admin access within the Resource Group. The controllers are scheduled onto the master nodes which then allows them to leverage this identity to create Azure infrastructure (load balancers, ip addresses etc)

The agent nodes are assigned an MSI that has the [Reader](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#reader) role scoped to the Resource Group. The auth tokens for this identity can be retrieved from the metadata endpoint and provide read-only access within the Resource Group.

Since Ark is scheduled onto the agent nodes, it will not have access to a token that can do anything meaningful. Also if Ark wants to reach outside of the Resource Group (typical for cross-region backup/restore) it will not be able to do this with this identity.

You could look at [User assigned identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/qs-configure-cli-windows-vmss#user-assigned-identity), but then it requires pre-provisioning of the identities and assignment to the VMs or VMSSs.

**AKS**

MSI is not enabled.

**Another option**

There is a project underway called [aad-pod-identity](https://github.com/Azure/aad-pod-identity) which allows operators to assign Azure Active Directory Identities to kubernetes applications.

The use cases align well with what we would be trying to achieve with Ark:

- Kubernetes applications depending on other applications that use AAD as an identity provider. These applications include Azure 1st party services (such as ARM, Azure sql or Azure storage) or user applications running on Azure (including same cluster) and or on premises.

> **Note:** Azure 1st party services are all moving to use AAD as the primary identity provider.

- Delegating authorization to user familiar tools such as AAD group memberships.

- Enable identity rotation without application interruption.

> **Example:** rotating a service principal password/cert without having to edit secrets assigned directly to applications.

- Provide a framework to enable enable time-boxed identity assignment. Manually triggered or automated. The same framework can be used for (jit sudo style access with automation tools).

> **Example:** a front end application can have access to centralized data store between midnight and 1 AM during business days only.

Additionally, as SPIFFE becomes more mature, the pod identity assertion within aad-pod-identity is expected to use SPIFFE pod identity. 

**Additional Info**

[Azure RBAC Roles](https://docs.microsoft.com/en-us/azure/role-based-access-control/rbac-and-directory-admin-roles#azure-rbac-roles)
[Configure a virtual machine scale set Managed Service Identity (MSI) using Azure CLI](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/qs-configure-cli-windows-vmss)
[How to use an Azure VM Managed Service Identity (MSI) for token acquisition](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/how-to-use-vm-token)
[Concept Documentation - Azure/aad-pod-identity](https://github.com/Azure/aad-pod-identity/blob/master/docs/design/concept.md)

Thoughts ?

For additional input - @khenidak, @sauryadas

**Comment by khenidak** [comment]
> Please note not all bootstrap tools are based on acs-engine and not all bootstrap tools assign the right permission to VMs/Masters

I want Azure add-ons to walk away from mounting azure.json and from trying to use VM identity. I would strongly use one of the following approaches:

1. Help the user to create service principal and assign the right permission to it. Mount it as secret into the pod. That way you are protected from what is defined for the VM on which your pods run on.
2. Use pod identity which pretty much allows the user to do that without explicitly mounting secrets

**Comment by ncdc** [comment]
@jcrowthe given the suggestions above, would it be ok to close this?

**Comment by arodriguezdlc** [comment]
It would be great if we could use aad pod identity to provide credentials to velero. Is it on the roadmap for this plugin?

**Comment by skriss** [comment]
@arodriguezdlc see WIP https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/29
