### ISSUE TITLE
Restore LimitRanges before Pods

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#385]
If a Pod is restored before a LimitRange that has defaults for requests and limits, the Pod misses out on the defaults. We should add `limitranges` to the default resource priorities

https://github.com/heptio/ark/blob/3172e907a13ed9993ec335efcee81b50ac2c6f12/pkg/cmd/server/server.go#L300-L307

**Comment by containscafeine** [comment]
Hey @ncdc, I tried adding `limitranges` to `defaultResourcePriorities`, and it worked (#392), but I was just curious about how pods are really restored? Is it that their parent controller (e.g. deployment) is restored and that takes care of running the pods again, or is that the pods along with their controllers are restored?
I'd assume it's the former, because LimitRange actually sets the resources in a pod, but the controller remains untouched. Is it?

**Comment by ncdc** [comment]
@containscafeine sorry for the delayed reply - I was traveling yesterday. Ark checks to see if an object has a controller ownerReference. If so, Ark does **not** restore the object, instead opting to allow the controller to create it.
