### ISSUE TITLE
All logs from Ark server containers on k8s/GKE show up in Stackdriver as ERROR logs

### ISSUE THREAD

**Issue by RochesterinNYC** [heptio/ark#507]
![screen shot 2018-05-18 at 5 00 55 pm](https://user-images.githubusercontent.com/1504464/40257704-27ecd050-5abd-11e8-883a-b599836699a0.png)

Example of a specific log message:

![redacted](https://user-images.githubusercontent.com/1504464/40257962-09290840-5abe-11e8-9568-14fb1d32406a.png)

(Notice the `ERROR` severity.)

We're using the default example Ark server Deployment available at https://github.com/heptio/ark/blob/master/examples/gcp/10-deployment.yaml

Does the Ark server log to stderr by default by any chance? We've seen this kind of behavior in the past with services that deploy to stderr (anything logged to stderr by a container in a k8s cluster will show up as ERROR logs in Stackdriver).

**Comment by ncdc** [comment]
Yes, it looks like logrus outputs to stderr by default.

**Comment by ncdc** [comment]
@mattmoyer @mauilion @craigtracey @fabioy @bryanl @timothysc @jbeda can you think of any reason we shouldn't change to logging to stdout by default?

**Comment by bryanl** [comment]
@ncdc if it isn’t an error, shouldn’t it go to stdout?

**Comment by ncdc** [comment]
That is the typical practice, yes. We honestly hadn't paid attention to it, and we just called `logrus.New()` which it turns out uses stderr by default. If/when we switch to stdout, all log messages (including error level) will go to stdout. Nothing will go to stderr unless it's emitted by some other code (i.e. not from logging).

**Comment by bryanl** [comment]
You can create a custom io.Writer that looks for error messages. It will send non-error messages to stdout and errors to stderr. (I'm sure you aren't using logrus.Fatal 😀). Then you can do `logrus.SetOutput(customWriter)`. This brings a new set of nuances, but should be manageable.

**Comment by ncdc** [comment]
I think I'd rather have everything that we log go to 1 file descriptor instead of 2.

**Comment by bryanl** [comment]
That makes sense. In that case, I'd send it all to stdout and let my log tooling figure it out.

**Comment by robbyt** [comment]
@ncdc I'm curious why you wouldn't want to use both stdout for normal logs and stderr for error-level logs?

**Comment by ncdc** [comment]
@robbyt in my experience, if you're using a single logger, I'd expect all log levels to go one place, unless you've configured separate files (foo.debug, foo.info, foo.warn, foo.error, etc).

Ark currently sends log lines to 3 different places: the Ark server pod's log (currently stderr of container, and what I'm suggesting should be stdout), individual backup log files, and individual restore log files. If we put the server log aside for the moment and focus on backup and restore log files, if we decided to split errors out from everything else, then we'd end up with 2 log files per backup or restore, which starts to get a bit messy.

Another reason for having a single output instead of multiple - it makes it much easier to review what happened when. Otherwise, you have to combine multiple log files/outputs together for a single timeline (which tools like lnav and es/kibana can certainly help with).

I'd like to hear more opinions and then hopefully we can come to an agreeable consensus. cc @skriss @jbeda @davecheney @fabioy @mattmoyer @asenchi @jrnt30 @lypht @rosskukulinski @craigtracey @timothysc @timoreimann @mauilion

**Comment by rosskukulinski** [comment]
My 2c:

1) We should not log everything to stderr
2) OK to pipe everything to stdout
3) If logs are not structured json output, I strongly recommend for users to parse and generate structured logs before final storage in elastic/s3/stackdriver.  This allows for simplied alerting/filtering/dashboards based on specific key/values (e.g. alert if more than 5 `error` logs in the last 1 minute)

**Comment by jonesg504** [comment]
Is there a temporary fix for this problem? Besides dumping all logs that are below ERROR?

**Comment by ncdc** [comment]
We'll get a fix in for v0.9.0 to switch to stdout.

**Comment by jonesg504** [comment]
Thanks!

**Comment by ncdc** [comment]
Fix is in #553
