### ISSUE TITLE
Enable sharing bucket between Ark and Restic

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/ark#576]
Right now Restic requires a separate bucket to be created with identical credentials as the main Ark server bucket.

For many users, having a separate bucket only makes the configuration & installation more complex.  Ark should allow sharing a bucket with Restic.

This would require creating root/parent-level directories to distinguish between backups and restic backup.  This would be a breaking change.

Perhaps we can link this with #103 which will also be having an impact on CRD compatibility.

**Comment by ncdc** [comment]
I do think that how we configure backup storage and restic storage will potentially change slightly as we do replication.

We also have #167 which is related

**Comment by skriss** [comment]
I'm leaning towards removing the ability for the location of the restic data to vary independently from the rest of the backup data, and just always making it a sub-dir of a backup storage location, e.g.:

```
<bucket> ark-backups
    cluster-1/
        _restic/
            ...
        backup-1/
            ...
        backup-2/
            ...
```
What do you all think about this? @rosskukulinski @ncdc @nrb @carlisia 

(by the way, using an `_` before `restic` would be an easy way for us to add structure to backup storage locations while still being able to support the legacy layout where backups are directly under the location, because backup names cannot start with an `_`.  So we'd know anything starting with an `_` is a system directory rather than a backup)

**Comment by ncdc** [comment]
+1 to them sharing the same bucket in the BSL.

We alternatively could do
```
<bucket>
  <cluster>
    <backups>
      backup1
    <restic>
      ns1
```

**Comment by skriss** [comment]
+1 to moving backups under a sub-dir too.  Are you saying use angle brackets to denote system dirs?  That works for me

**Comment by ncdc** [comment]
No angle brackets. Those are variables.

```
(bucket=foo)
  cluster=abc
    backups
      my-backup1
      my-backup2
    restic
      my-namespace
```

We could even make a `clusters` dir as the root in the bucket/prefix.

**Comment by nrb** [comment]
I like the proposed root/cluster/(backups,restic) approach.

Would `root/clusters/my-cluster` only be owned by `my-cluster`? We might need to brainstorm a bit on how that would work on migration restores - not that it's necessarily difficult, I just don't think we'd discussed that layout yet.

**Comment by ncdc** [comment]
Actually I'm not sure we need to force a `clusters` dir. That could be part of the prefix, at the user's discretion. Essentially, Ark would have full control over the contents inside bucket+prefix, which would be to have a "backups" dir for backups and a "restic" dir for restic snapshots.

We talked briefly before about what the process would look like for a new cluster to take over ownership of some other cluster's bucket+prefix. I believe we talked about using some files in the bucket to indicate a takeover, and requiring a human to issue a manual command that would overwrite the cluster id in s3 (so ark would see that the new cluster now owns it). But this needs more fleshing out.

**Comment by nrb** [comment]
Yep, that's my recollection, too. We'd also discussed that in the case of replication, a user may want to restore from a BSL that the current cluster doesn't own. We were thinking of making some directory (maybe `restores`) writeable by any Ark cluster so that restore logs aren't completely lost. I think whether it's a top level dir or space in `backups` is probably up for discussion though.

**Comment by ncdc** [comment]
Having a new `restores` dir inside bucket+prefix and moving the restore logs there makes sense to me. It keeps the backup dirs "pristine".

**Comment by carlisia** [comment]
👍 from me.
