### ISSUE TITLE
Finalize DownloadRequest CRD

### ISSUE THREAD

**Issue by ncdc** [heptio/ark#603]
Should we continue to use a single DownloadRequest "union" to support downloading different types of files, or should we use 1 CRD per type?

**Comment by skriss** [comment]
@ncdc I haven't experienced any issues with the current CRD, and it's pretty straightforward to add a new type (did so for v0.10).  I think there is definitely a "simplicity" argument in favor of sticking with just the one.  Did you have any specific reasons in mind for breaking it out?

**Comment by ncdc** [comment]
@skriss mainly to avoid the switch statement around the different types and the fact that some of them (restore related) require the backup directory name which isn't always the same as the restore name.

**Comment by skriss** [comment]
Got it.  The restore-related ones no longer require the backup name since we've moved restores into their own  subdir within object storage (though the controller does still have to get the backup to figure out which backup storage location the backup is in).

My personal preference would be to leave this as-is.  Open to other views though.

**Comment by ncdc** [comment]
It's worked well since we first added it, and it's not really causing any problems. I'll close it and if we need to, we can reopen for 2.x.
