### ISSUE TITLE
Update restore process to use the appropriate locations (snapshot, destination for volume create) when doing PV restores

### ISSUE THREAD

**Issue by skriss** [heptio/ark#808]
Ark currently assumes there's only one location for snapshots and creating new disks. The restore process (the controller and `restore` package) will need to be updated to inspect the relevant `Backup` and use the right locations.

- pkg/restore will get a list of the VolumeSnapshot objects that are associated with the backup being restored
- restore will either use backup.spec.volumeSnapshotLocations or the list of VSLs from the previous step to identify the locations where snapshots exist
- restore will instantiate a BlockStore per VSL and use it to execute CreateVolumeFromSnapshot
- TODO: figure out UX around how we figure out where the nodes are/where the volume should be created. Currently, we always restore into the same AZ as the original backed-up volume, but that's not ideal. (also consider how this changes in v0.11 with replication)

**Comment by skriss** [comment]
@wwitzel3 @carlisia - since we're switching to storing snapshot info in VolumeSnapshot API objects a/o v0.10, I'm wondering if we want be backwards-compatible for restores - so, if there's an existing backup in object storage, that has `.status.volumeBackupInfo`, should Ark v0.10 support restoring it?  I'm tempted to say yes, **if** there's only a single VolumeSnapshotLocation configured, so we trivially know where the snapshots are located.  I think if we don't do this, we're going to potentially get a lot of issues/complaints about not being compatible.  I think we can plan to remove this code for v1.0.  WDYT?

**Comment by wwitzel3** [comment]
I think this makes sense. When you say single VolumeSnapshotLocation, you mean, only one provider configured? I know we only allow one per provider, so just wanted to be sure I'm understanding you right.

Would we want to give the 0.10 client a way to specify the provider in that case? Since it would be being removed in 1.0 or even 0.11? So log/warn that the restore is using the old format if there is a single provider, log/error and provide a CLI example of specifying a provider for the restore? `--deprecated-restore-provider` ? Really just thinking out loud here.

I think going through the exercise of deprecating and rolling off of an API/file format would be good practice in general.

**Comment by skriss** [comment]
@wwitzel3 have you made any progress on this?  Some of it is going to need to change based on the discussion we just had so just trying to get a sense of where it is.  Happy to help out if needed.

**Comment by wwitzel3** [comment]
Yeah, so based on what we talked about for #863, should I rebase this off #922?

**Comment by skriss** [comment]
Yes, you'll want to use the BackupStore's `GetBackupVolumeSnapshots` to get the snapshot & location info.
