### ISSUE TITLE
ark on private k8s cluster

### ISSUE THREAD

**Issue by thdrnsdk** [heptio/ark#841]
hello team, i'm looking for ark on private cluster env.

i want to object, pv backup and restore without buckets.

Is there any way to specify "restic-location" options without bucket?

i found the issue #772

if update doc, dos this helpful for me?

**Comment by nrb** [comment]
Thanks for the question @thdrnsdk!

Right now, Ark focuses on sending backup tarballs of Kubernetes objects and restic backups to an object storage provider. We've had discussions about sending the Kubernetes to git storage, but we haven't discussed alternatives for restic yet.

One alternative may be setting up a [Minio](https://www.minio.io/) installation inside your network that Ark/Restic could use, since it provides and S3 API.

Does this answer your question? What storage system do you currently have in place?

**Comment by thdrnsdk** [comment]
thanks for fast answer @nrb 

we consider on private cluster befind the firewall. that means out clusters are disconnected from the external internet environment.
so i want to use backup with out any public provider storage

currently the storage we use is only nfs for k8s pv. 

Is there a way to use ark in this situation?

**Comment by nrb** [comment]
Alright @thdrnsdk, that makes sense. We've had this question asked before, and #772 is our attempt to clarify that Ark can be run behind a firewall, without a cloud provider, and it's currently incomplete.

Ark still relies on an object storage provider to store the backup files and Restic snapshots.

Minio is a project that provides object storage inside your own cluster, off the internet, with an AWS S3-compatible API. Ark can back up to a Minio cluster running inside your internal network.

Ceph also provides a AWS S3-compatible API, and we've had users successfully back up to private Ceph clusters.

Does that answer your question? I apologize for the delays on the documentation, we hope to merge the PR and make this information easier to find soon, but the team is in meetings and traveling for the rest of the week.

**Comment by thdrnsdk** [comment]
thank you! your reply very helpful for our project plan.

**Comment by nrb** [comment]
Thanks for your interest! I'm going to close this issue for now, but if you need more clarification please feel free to open a new issue, comment on the documentation PR, or open a new issue.
