### ISSUE TITLE
Don't require default volume snapshot location to be specified for a provider if only 1 exists

### ISSUE THREAD

**Issue by skriss** [heptio/ark#995]
Right now, if you don't specify a default VSL for a provider and you don't specify the name of a VSL when creating a backup, you won't get snapshots.  This is overly burdensome for the typical case of "one provider, one snapshot location".  In the case where a provider has a single VSL, we should automatically use that.  Specifying a default should only be necessary in the case of >1.

I think the changes probably need to be made here: https://github.com/heptio/ark/blob/master/pkg/controller/backup_controller.go#L302

**Comment by carlisia** [comment]
What to do in this scenario:
 - only 1 vsl
 - vsl location is named `primary`
 - user sets default to `random`

**Comment by nrb** [comment]
My assumption is that this issue was created for this case, as per `Specifying a default should only be necessary in the case of >1.`

* 1 VSL
* VSL named whatever the user wants
* user did not specify the `--default-volume-snapshot-location` argument

I'll think on this second scenario. At first glance, it looks like we were given contradictory information by the user and should notify them; it's hard to know their intention here.

**Comment by nrb** [comment]
My assumption of what the code meant to solve the case I just posted would do when it encounters this contradictory case: The `primary` location can be used if specified on a backup, but no defaulting will be done because `random` isn't made yet.

While I can reason that out as someone who's worked on this, I think in general our signaling of this kind of state contradiction needs deeper thought.

**Comment by carlisia** [comment]
I just had an idea. What if we think the opposite way.

- Admin boots up ark with vsl default set to `random`.
- User creates vsl named `primary`

Obviously in this case the user will not have access to the `default` feature.

**Comment by skriss** [comment]
This was closed by #1009
